[build]
builder = "nixpacks"

[deploy]
startCommand = "/opt/venv/bin/python backend/manage.py migrate && /opt/venv/bin/gunicorn core.wsgi --chdir backend --bind 0.0.0.0:$PORT --log-file -"
restartPolicyType = "on_failure"
