[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --log-file -"
restartPolicyType = "on_failure"
